<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proxy HTTP</title>
</head>
<body>
    <h1>Proxy HTTP</h1>
    <input type="text" id="url" placeholder="Enter URL" />
    <button onclick="submitForm()">Make a Request</button>
    <button onclick="submitForm1()">Make a Request using Mongo</button>
    <div id="result"></div>
    <script>
        // let startTime, endTime
        // async function makeRequest(num) {
        //     startTime = Date.now()
        //     const promises = new Array(num)
        //                         .fill(1)
        //                         .map((_, index) => fetch('http://localhost:3000/users'))
        //     const responses = await Promise.all(promises)
        //     endTime = Date.now()
        //     console.log(startTime, endTime, endTime-startTime, responses)
        //     document.getElementById('result').innerHTML = responses ;
        // }
        // async function makeRequestMon(num) {
        //     startTime = Date.now()
        //     const promises = new Array(num)
        //                         .fill(1)
        //                         .map((_, index) => fetch('http://localhost:3001/api/posts'))
        //     const responses = await Promise.all(promises)
        //     endTime = Date.now()
        //     console.log(startTime, endTime, endTime-startTime, responses)
        //     document.getElementById('result').innerHTML = responses.body ;
        // }
        let startTime, endTime
        async function submitForm() {
        
        const originalUrl = document.getElementById("url").value;
        
        try {
          const data = await makeRequest(originalUrl);
          document.getElementById("result").innerText = JSON.stringify(
            data,
            null,
            2
          );
        } catch (error) {
          console.error(error);
          // Handle error, e.g., display an error message to the user
        }
      }
    
      async function makeRequest(url) {
        console.log("making a request");
        // const params = new URLSearchParams({ url });
        startTime = Date.now()
        try {
          const response = await fetch(`http://localhost:3000/${url.toString()}`, {
            method: "GET",
          });
        endTime = Date.now()
        console.log(endTime-startTime)
    
          if (!response.ok) {
            // Handle non-successful response (e.g., HTTP status other than 200)
            throw new Error(`Request failed with status: ${response.status}`);
          }
    
          const data = await response.json();
          console.log(data);
          return data;
        } catch (error) {
          console.error(error);
          // Rethrow the error to be caught by the calling function
          throw error;
        }
      }
      async function submitForm1() {
        const originalUrl = document.getElementById("url").value;
        
        try {
          const data = await makeRequest1(originalUrl);
          document.getElementById("result").innerText = JSON.stringify(
            data,
            null,
            2
          );
        } catch (error) {
          console.error(error);
          // Handle error, e.g., display an error message to the user
        }
      }
    
      async function makeRequest1(url) {
        console.log("making a request");
        // const params = new URLSearchParams({ url });
        startTime = Date.now()
        try {
          const response = await fetch(`http://localhost:3001/api/${url.toString()}`, {
            method: "GET",
          });
        endTime = Date.now()
        console.log(endTime-startTime)
    
          if (!response.ok) {
            // Handle non-successful response (e.g., HTTP status other than 200)
            throw new Error(`Request failed with status: ${response.status}`);
          }
    
          const data = await response.json();
          console.log(data);
          return data;
        } catch (error) {
          console.error(error);
          // Rethrow the error to be caught by the calling function
          throw error;
        }
      }
    </script>
</body>
</html>